---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: pre-run | update package cache (debian, etc)
    tags: always
    apt: update_cache=yes
    changed_when: False
    when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - vim-nox
        - dconf-cli
        - python3-psutil
        - mc

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: thierry
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: thierry
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/15"
      job: ansible-pull -o -U https://github.com/trgmd68/ansible_desktop.git

  - name: cleanup package cache (debian and ubuntu)
    tags: always
    apt:
      autoclean: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]

